Repository aws/aws-sdk-java-v2, pull requests merged in 2025-06, with the labels that each got.

#6149 Remove pid file
  .attach_pid885
Labels: changelog-not-required

#6150 Fix NPE in ProfileFileSupplier.defaultSupplier
  .changes/next-release/bugfix-AWSSDKforJavav2-30203bb.json
  core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFile.java
  core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileSupplier.java
  core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileSupplierTest.java
  core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileTest.java
Labels: no-api-surface-area-change

#6155 docs: add jencymaryjoseph as a contributor for code
  .all-contributorsrc
  README.md
Labels: changelog-not-required

#6151 S3 transfer manager client constructor and method recipe
  test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/after/src/main/java/foo/bar/TransferManagerS3.java
  test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/before/src/main/java/foo/bar/TransferManagerS3.java
  v2-migration/src/main/java/software/amazon/awssdk/v2migration/TransferManagerMethodsToV2.java
  v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml
  v2-migration/src/main/resources/META-INF/rewrite/change-transfer-manager-simple-methods.yml
  v2-migration/src/main/resources/META-INF/rewrite/change-transfer-manager-types.yml
Labels: changelog-not-required

#6083 Adding functionality to config preferred authschemeProvider
  .changes/next-release/feature-AWSSDKforJavav2-8e1c19d.json
  codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/AuthSchemeGeneratorTasks.java
  codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeProviderSpec.java
  codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecUtils.java
  codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/PreferredAuthSchemeProviderSpec.java
  codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java
  codegen/src/test/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecTest.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-preferred-provider.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-provider.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-provider.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-bearer-auth-client-builder-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-endpoints-auth-params.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-internal-defaults-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-composed-sync-default-client-builder.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-multi-auth-sigv4a-client-builder-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-ops-client-builder-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-service-client-builder-class.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-query-client-builder-class.java
  core/aws-core/src/main/java/software/amazon/awssdk/awscore/auth/AuthSchemePreferenceResolver.java
  core/aws-core/src/test/java/software/amazon/awssdk/awscore/internal/auth/AuthSchemePreferenceResolverTest.java
  core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java
  services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtensionTest.java
  test/codegen-generated-classes-test/src/main/resources/codegen-resources/multiauth/service-2.json
  test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/PreferredAuthSchemeProviderTest.java
  test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/multiauth/AuthSchemePreferenceResolverFunctionalTest.java
Labels: api-surface-area-approved-by-team

#6162 Removing S3 dependency in URL client
  http-clients/url-connection-client/pom.xml
  services/s3/pom.xml
  services/s3/src/it/java/software/amazon/awssdk/services/s3/urlconnection/EmptyFileS3IntegrationTest.java
  services/s3/src/it/java/software/amazon/awssdk/services/s3/urlconnection/HeadObjectIntegrationTest.java
  services/s3/src/it/java/software/amazon/awssdk/services/s3/urlconnection/S3WithUrlHttpClientIntegrationTest.java
  services/s3/src/it/java/software/amazon/awssdk/services/s3/urlconnection/UrlHttpConnectionS3IntegrationTestBase.java
Labels: changelog-not-required, no-api-surface-area-change

#6179 Invalid link link in deprecated message of DefaultCredentialsProvider replaced to @code
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java
Labels: no-api-surface-area-change

#6195 Migration tool recipe for adding comments for unsupported methods
  test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/after/src/main/java/foo/bar/TransferManagerS3.java
  test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/before/src/main/java/foo/bar/TransferManagerS3.java
  v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3AddImportsAndComments.java
  v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3TmAddComments.java
  v2-migration/src/main/java/software/amazon/awssdk/v2migration/TransferManagerMethodsToV2.java
  v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java
  v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml
  v2-migration/src/main/resources/META-INF/rewrite/change-transfer-manager-simple-methods.yml
Labels: changelog-not-required

#6176 EC2 IMDS Changes to Support Account ID
  .changes/next-release/feature-AWSEC2-9b178a4.json
  core/auth/pom.xml
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/HttpCredentialsLoader.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/EC2MetadataServiceMock.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderExtendedApiTest.java
  core/regions/pom.xml
  core/regions/src/main/java/software/amazon/awssdk/regions/util/HttpResourcesUtils.java
Labels: no-api-surface-area-change

#6207 Add support for protocol test error cases + add cbor error cases
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/unmarshalling/UnmarshalledErrorAssertion.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/unmarshalling/UnmarshallingTestContext.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/model/Then.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/model/When.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/model/WhenAction.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/reflect/ShapeModelReflector.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/runners/ProtocolTestRunner.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/runners/UnmarshallingTestRunner.java
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-output.json
  test/protocol-tests/src/main/resources/codegen-resources/sdkrpcv2/service-2.json
Labels: changelog-not-required
