Repository aws/aws-sdk-java-v2, pull requests merged in 2025-09, with the labels that each got.

#6399 Fix flakey S3 Multipart tests
  services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientGetObjectRetryBehaviorWiremockTest.java
  services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientGetObjectWiremockTest.java
Labels: changelog-not-required

#6396 Make test more reliable
  services/sts/src/it/java/software/amazon/awssdk/services/sts/AssumeRoleIntegrationTest.java
Labels: changelog-not-required

#6395 Add utils-lite package
  .brazil.json
  bom/pom.xml
  pom.xml
  test/architecture-tests/pom.xml
  test/architecture-tests/src/test/java/software/amazon/awssdk/archtests/UtilsLitePackageTest.java
  test/http-client-benchmarks/pom.xml
  test/sdk-benchmarks/pom.xml
  test/tests-coverage-reporting/pom.xml
  utils-lite/pom.xml
  utils-lite/src/main/java/software/amazon/awssdk/utilslite/SdkInternalThreadLocal.java
  utils-lite/src/test/java/software/amazon/awssdk/utilslite/ThreadStorageTest.java
Labels: api-surface-area-approved-by-team

#6420 Flaky test fix for StoringSubscriberTest
  utils/src/test/java/software/amazon/awssdk/utils/async/StoringSubscriberTest.java
Labels: changelog-not-required

#6446 Optimizations for EnhancedDocument.toJson()
  .changes/next-release/bugfix-AmazonDynamoDBEnhancedClient-18f50d7.json
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/JsonStringFormatHelper.java
Labels: no-api-surface-area-change

#6456 Revert "Add Business Metrics for Credential Providers (#6443)"
  .changes/next-release/feature-AWSSDKforJavav2-c2d8ec6.json
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ChildProfileCredentialsProviderFactory.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/EnvironmentVariableCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/HttpCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileProviderCredentialsContext.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/StaticCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/SystemPropertyCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java
  core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/WebIdentityTokenCredentialProperties.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProviderTest.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProviderTest.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/StaticCredentialsProviderTest.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/SystemSettingCredentialsProvidersTest.java
  core/auth/src/test/java/software/amazon/awssdk/auth/credentials/SystemSettingsCredentialsProviderTest.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApplyUserAgentStage.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/useragent/BusinessMetricFeatureId.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApplyUserAgentStageTest.java
  services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProvider.java
  services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoProfileCredentialsProviderFactory.java
  services/sso/src/test/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProviderTest.java
  services/sso/src/test/java/software/amazon/awssdk/services/sso/auth/SsoProfileCredentialsProviderFactoryTest.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithWebIdentityCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetFederationTokenCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetSessionTokenCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenFileCredentialsProvider.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/AssumeRoleWithWebIdentityRequestSupplier.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsProfileCredentialsProviderFactory.java
  services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsWebIdentityCredentialsProviderFactory.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProviderTest.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProviderTest.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithWebIdentityCredentialsProviderTest.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsGetFederationTokenCredentialsProviderTest.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsGetSessionTokenCredentialsProviderTest.java
  services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenCredentialsProviderBaseTest.java
  test/auth-tests/pom.xml
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/ContainerCredentialsProviderUserAgentTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/EnvironmentVariableCredentialsProviderUserAgentTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/ImdsUserAgentProviderTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/ProcessCredentialsProviderUserAgentTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/ProfileCredentialProviderUserAgentTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/SystemPropertyCredentialsProviderUserAgentTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/source/UserAgentProviderTest.java
  test/auth-tests/src/it/java/software/amazon/awssdk/auth/sts/StsCredentialsProviderUserAgentTest.java
Labels: no-api-surface-area-change
