Repository aws/aws-sdk-java-v2, pull requests merged in 2025-07, with the labels that each got.

#6230 Add Query Compatible protocol tests
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/model/TestCase.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/model/Then.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/runners/ProtocolTestRunner.java
  test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/runners/UnmarshallingTestRunner.java
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-querycompatible-input.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-querycompatible-output.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-nonquerycompatible-input.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-nonquerycompatible-output.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-querycompatible-input.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-querycompatible-output.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/json-querycompatible-suite.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/smithy-rpcv2-nonquerycompatible-suite.json
  test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/smithy-rpcv2-querycompatible-suite.json
  test/protocol-tests/src/main/resources/codegen-resources/json-querycompatible/customization.config
  test/protocol-tests/src/main/resources/codegen-resources/json-querycompatible/endpoint-rule-set.json
  test/protocol-tests/src/main/resources/codegen-resources/json-querycompatible/endpoint-tests.json
  test/protocol-tests/src/main/resources/codegen-resources/json-querycompatible/service-2.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-nonquerycompatible/customization.config
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-nonquerycompatible/endpoint-rule-set.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-nonquerycompatible/endpoint-tests.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-nonquerycompatible/service-2.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-querycompatible/customization.config
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-querycompatible/endpoint-rule-set.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-querycompatible/endpoint-tests.json
  test/protocol-tests/src/main/resources/codegen-resources/rpcv2-querycompatible/service-2.json
  test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/JsonQueryCompatibleProtocolTest.java
  test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/SmithyRpcV2CborNonQueryCompatibleProtocolTest.java
  test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/SmithyRpcV2CborQueryCompatibleProtocolTest.java
Labels: changelog-not-required

#6254 Improve error message for the error case where a request using Reques…
  .changes/next-release/bugfix-AWSSDKforJavav2-1c39709.json
  core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java
Labels: no-api-surface-area-change

#6261 Fix service version info to only register major and minor versions
  codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ServiceVersionInfoSpec.java
  codegen/src/main/java/software/amazon/awssdk/codegen/utils/VersionUtils.java
  codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/ServiceVersionInfoSpecTest.java
  codegen/src/test/java/software/amazon/awssdk/codegen/utils/VersionUtilsTest.java
  codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/specs/test-service-version-info-class.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/useragent/SdkUserAgentBuilderTest.java
  test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BusinessMetricsUserAgentTest.java
Labels: changelog-not-required

#6276 Fix dependency generation for new smithy-rpc-v2-cbor services
  release-scripts/src/main/java/software/amazon/awssdk/release/CreateNewServiceModuleMain.java
  release-scripts/src/main/java/software/amazon/awssdk/release/NewServiceMain.java
Labels: changelog-not-required, no-api-surface-area-change

#6264 Support trailers in chunked publisher
  core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedPublisher.java
  core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedPublisherTest.java
Labels: changelog-not-required
