Repository aws/aws-sdk-java-v2, pull requests merged in 2025-08, with the labels that each got.

#6312 Update Apache HttpClient 5 to use recommended APIs and remove deprecated code
  .changes/next-release/feature-ApacheHTTPClient5-bd35717.json
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/Apache5HttpClient.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/Apache5HttpRequestConfig.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/conn/ClientConnectionManagerFactory.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/conn/ClientConnectionRequestFactory.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/conn/SdkTlsSocketFactory.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/impl/Apache5HttpRequestFactory.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/impl/Apache5SdkHttpClient.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/net/DelegateSocket.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/net/SdkSocket.java
  http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/utils/Apache5Utils.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5ClientTlsAuthTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5ClientTlsHalfCloseTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5HttpClientUriSanitizationTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5HttpClientWireMockTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5HttpClientWithSocketFactoryWireMockTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/MetricReportingTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/internal/conn/IdleConnectionReaperTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/internal/conn/SdkTlsSocketFactoryTest.java
  http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/internal/impl/ApacheHttpRequestFactoryTest.java
Labels: api-surface-area-approved-by-team

#6304 Truncate to content in chunked publisher
  core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedPublisher.java
  core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedPublisherTest.java
  utils/src/main/java/software/amazon/awssdk/utils/async/ContentLengthAwareSubscriber.java
  utils/src/test/java/software/amazon/awssdk/testutils/PublisherUtils.java
  utils/src/test/java/software/amazon/awssdk/utils/async/ContentLengthAwareSubscriberTckTest.java
  utils/src/test/java/software/amazon/awssdk/utils/async/ContentLengthAwareSubscriberTest.java
Labels: changelog-not-required, no-api-surface-area-change

#6316 Log errors instead of throwing errors for duplicate keys in ImmutableMap
  .changes/next-release/bugfix-AWSSDKforJavav2-01696b7.json
  codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/ServiceMetadataGenerator.java
  codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/s3-service-metadata.java
  codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/sts-service-metadata.java
  utils/src/main/java/software/amazon/awssdk/utils/ImmutableMap.java
  utils/src/test/java/software/amazon/awssdk/utils/ImmutableMapTest.java
Labels: api-surface-area-approved-by-team

#6329 Add ability to specify transferDirectoryMaxConcurrency in S3TransferManager
  .changes/next-release/feature-S3TransferManager-ca5314b.json
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DownloadDirectoryHelper.java
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/TransferConfigurationOption.java
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/TransferManagerConfiguration.java
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/TransferManagerFactory.java
  services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelper.java
  services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DownloadDirectoryHelperTest.java
  services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/TransferManagerConfigurationTest.java
  services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelperTest.java
Labels: api-surface-area-approved-by-team

#6340 Event stream response handler builder onError documentation improvement
  .changes/next-release/documentation-AWSSDKforJavav2-6b16da2.json
  core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamResponseHandler.java
Labels: no-api-surface-area-change

#6347 SdkException java doc changed
  core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkException.java
Labels: changelog-not-required, no-api-surface-area-change

#6348 Avoid extra byte array copying when downloading to memory with AsyncResponseTransformer
  .changes/next-release/feature-AWSSDKforJavav2-d4e19d2.json
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncResponseTransformer.java
Labels: api-surface-area-approved-by-team

#6355 Avoid extra byte array copying when downloading to memory with AsyncResponseTransformer
  .changes/next-release/feature-AWSSDKforJavav2-dd9f8bf.json
  core/sdk-core/src/main/java/software/amazon/awssdk/core/ResponseBytes.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncResponseTransformer.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/ResponseBytesTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBodyTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/PublisherAsyncResponseTransformerTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingPublisherTestUtils.java
Labels: api-surface-area-approved-by-team

#6368 Stream based upload retry support
  .changes/next-release/deprecation-AWSSDKforJavav2-6069419.json
  .changes/next-release/feature-AWSSDKforJavav2-500254f.json
  .changes/next-release/feature-AWSSDKforJavav2-72c5f55.json
  .changes/next-release/feature-AWSSDKforJavav2-ed2c57a.json
  core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/async/BufferedSplittableAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/async/CloseableAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/async/listener/AsyncRequestBodyListener.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteBuffersAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/NonRetryableSubAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/RetryableSubAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingPublisher.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SubAsyncRequestBody.java
  core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SubAsyncRequestBodyConfiguration.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodySplitConfigurationTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/ByteBufferAsyncRequestBodyTckTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/ByteBuffersAsyncRequestBodyTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBodySplitHelperTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/NonRetryableSubAsyncRequestBodyTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/RetryableSubAsyncRequestBodyTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingPublisherTest.java
  core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingPublisherTestUtils.java
  services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3MultipartClientPutObjectIntegrationTest.java
  services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriber.java
  services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartUploadHelper.java
  services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithKnownContentLengthHelper.java
  services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java
  services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriberTest.java
  services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientPutObjectWiremockTest.java
  services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelperTest.java
  services/s3/src/test/resources/log4j2.properties
  test/architecture-tests/src/test/java/software/amazon/awssdk/archtests/CodingConventionWithSuppressionTest.java
  test/s3-tests/src/it/java/software/amazon/awssdk/services/s3/regression/upload/UploadStreamingRegressionTesting.java
Labels: api-surface-area-approved-by-team
