Repository aws/aws-sdk-java-v2, pull requests merged in 2025-05, with the labels that each got.

#6076 Add changelog verification yaml
  .github/workflows/changelog-verification.yml
Labels: no-changelog

#6056 Add retry tests for request bodies
  test/s3-tests/pom.xml
  test/s3-tests/src/test/java/software/amazon/awssdk/services/s3/AsyncRequestBodyRetryTest.java
  test/s3-tests/src/test/java/software/amazon/awssdk/services/s3/BaseRequestBodyRetryTest.java
  test/s3-tests/src/test/java/software/amazon/awssdk/services/s3/ChunkedDecoder.java
  test/s3-tests/src/test/java/software/amazon/awssdk/services/s3/SyncRequestBodyRetryTest.java
  test/s3-tests/src/test/java/software/amazon/awssdk/services/s3/TestServer.java
  test/s3-tests/src/test/resources/log4j2.xml
  test/s3-tests/src/test/resources/software/amazon/awssdk/services/s3/mock-keystore.jks
Labels: no-changelog

#6091 Use Javadoc snippets
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbAttribute.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbBean.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbIgnore.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbIgnoreNulls.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbImmutable.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbPartitionKey.java
  services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbSortKey.java
Labels: no-changelog

#6094 Separate migration tests from regular builds
  .github/workflows/codebuild-ci.yml
  buildspecs/migration-test.yml
  buildspecs/resources/ci.cloudformation.yml
  pom.xml
  test/v2-migration-tests/pom.xml
Labels: no-changelog

#6106 Delete unncessary file
  .attach_pid881
Labels: no-changelog

#6099 Add CI for api surface area review verification
  .github/workflows/api-surface-area-review-verification.yml
Labels: no-changelog

#6116 Create a variable for modules to skip
  buildspecs/release-javadoc.yml
  buildspecs/release-to-maven.yml
Labels: changelog-not-required

#6117 Add CodeQL CI
  .github/workflows/codeql.yml
Labels: changelog-not-required

#6118 Add script to automatically set up a new module
  scripts/setup-new-module
Labels: changelog-not-required

#6138 Remove unneeded bundle dependency
  test/s3-tests/pom.xml
Labels: changelog-not-required, no-api-surface-area-change
